# Generated by Django 5.0.1 on 2024-02-23 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_education', models.CharField(max_length=255)),
                ('educational_degree', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('number_of_spec', models.PositiveIntegerField(default=0)),
                ('name_of_spec', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('educational_program', models.TextField()),
                ('offer_type', models.CharField(max_length=150)),
                ('license_scope', models.PositiveIntegerField(default=0)),
                ('contract', models.PositiveIntegerField(default=0)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('average_contract_mark', models.FloatField()),
                ('average_budget_mark', models.FloatField()),
                ('time_of_study', models.PositiveIntegerField()),
                ('examination_coefficients', models.JSONField(blank=True)),
                ('slug', models.SlugField(null=True)),
                ('characteristic', models.TextField()),
                ('future', models.TextField()),
            ],
            options={
                'ordering': ('-average_budget_mark',),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='specialties.specialty')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='specialty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_list', to='specialties.university'),
        ),
    ]
